name: testing_wine_project_file #name of the file
on: [push] # on event
jobs: #jobs to run
  run:
    runs-on: [ubuntu-latest] # this show which os we want to run it.
    container: docker://dvcorg/cml-py3:latest # docker container
    steps:
      -uses: actions/checkout@v3 # it will checkout the actions from github actions
      -name: cml_run #name of the stemsp
       env:
        repo-token: $ {{secrets.GITHUB.TOKEN}} #this show the repository access of of github
       run: # what are the commands needs to run
          pip install -r requirement.txt
          python train.py
          echo "Model metrics"
          cat metrics.txt